version: "3.9"

services:
  server: 
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - ./.env
    depends_on: 
      - mysql
    volumes:
      - .:/work
  
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discord_channel_management_bot_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes: 
  mysql-data: 

